<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="yawlsimulator" nsURI="http://org.pnml.tools/epnk/types/yawl/simulator"
    nsPrefix="yawlsimulator">
  <eClassifiers xsi:type="ecore:EClass" name="EnabledTransition" eSuperTypes="../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inArcs" upperBound="-1"
        eType="#//SelectArc" eOpposite="#//SelectArc/targetTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outArcs" upperBound="-1"
        eType="#//SelectArc" eOpposite="#//SelectArc/sourceTransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectArc" eSuperTypes="../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTransition" eType="#//EnabledTransition"
        eOpposite="#//EnabledTransition/outArcs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetTransition" eType="#//EnabledTransition"
        eOpposite="#//EnabledTransition/inArcs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marking" eSuperTypes="../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//TextualAnnotation ../../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
